namespace: three-tier

replicaCount: 1

image:
  repository: 755395261332.dkr.ecr.ap-south-2.amazonaws.com/b-end
  tag: 8
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-registry-secret

service:
  type: ClusterIP
  port: 3500

env:
  mongo:
    secretName: mongo-sec

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 5

  readiness:
    path: /ready
    initialDelaySeconds: 10
    periodSeconds: 5

  startup:
    path: /started
    periodSeconds: 10
    failureThreshold: 30
